// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVvg-3QgCKKdlgvJu9YqGfjezhySGELrc',
    appId: '1:484800123364:web:dad8d3ea3e90d88aa737f1',
    messagingSenderId: '484800123364',
    projectId: 'minprojectapi',
    authDomain: 'minprojectapi.firebaseapp.com',
    storageBucket: 'minprojectapi.appspot.com',
    measurementId: 'G-4FZH0D66XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVH3zndAFH-tNAnhRBBQj5rvwV4gkiGEo',
    appId: '1:484800123364:android:841152d8da07c25ca737f1',
    messagingSenderId: '484800123364',
    projectId: 'minprojectapi',
    storageBucket: 'minprojectapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrmpaaXJrSVH6eqXHX4ZWZydXnKE9vOa0',
    appId: '1:484800123364:ios:6af1085384ab362ba737f1',
    messagingSenderId: '484800123364',
    projectId: 'minprojectapi',
    storageBucket: 'minprojectapi.appspot.com',
    iosClientId: '484800123364-uto50u3k7ckgc3a7n3588f3g5h2k521a.apps.googleusercontent.com',
    iosBundleId: 'com.miny.flutterApiProjext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrmpaaXJrSVH6eqXHX4ZWZydXnKE9vOa0',
    appId: '1:484800123364:ios:6af1085384ab362ba737f1',
    messagingSenderId: '484800123364',
    projectId: 'minprojectapi',
    storageBucket: 'minprojectapi.appspot.com',
    iosClientId: '484800123364-uto50u3k7ckgc3a7n3588f3g5h2k521a.apps.googleusercontent.com',
    iosBundleId: 'com.miny.flutterApiProjext',
  );
}
